[build]
  publish = "."
 functions = "netlify"

[[redirects]]
  from = "/api/login"
  to = "/.netlify/functions/login"
  status = 200

[[redirects]]
  from = "/api/session"
  to = "/.netlify/functions/session"
  status = 200

[[redirects]]
  from = "/api/set-password"
  to = "/.netlify/functions/set-password"
  status = 200

[[redirects]]
  from = "/api/kiwify"
  to = "/.netlify/functions/kiwify-webhook"
  status = 200
